# Base directory
export ASTROSOFT=/HOPS_SOFT


# PGPLOT
export PGPLOT_DIR=$ASTROSOFT/pgplot

# LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib:/usr/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ASTROSOFT/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ASTROSOFT/fftw-3.3.8/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ASTROSOFT/share/ghostscript/9.25/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PGPLOT_DIR


# PKG_CONFIG_PATH
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$ASTROSOFT/lib/pkgconfig

# PATH
export PATH=$PATH:$ASTROSOFT/bin:$PGPLOT_DIR


# INCLUDE_PATH
export C_INCLUDE_PATH=$ASTROSOFT/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$ASTROSOFT/include:$CPLUS_INCLUDE_PATH 